spring:
  application:
    name: ImoocMerchants
  datasource:
    url: jdbc:mysql://123132465465/passbook?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 1321654
  kafka:
    bootstrap-servers: 123123465:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: imooc-merchants.log

